### ISSUE TITLE
cpp-client loses spans on short-lived processes; Close() not flushing buffers?

### ISSUE THREAD

**Issue by ringerc** [jaegertracing/cpp-client#52]
If a process:

* Creates a tracer with a typical configuration (like the following yml)
* Creates a span
* Finishes the span
* Closes the tracer
* Exits

the span should be reported to the collector. But it isn't unless a short sleep is inserted *before* the `tracer->Close()` call.

If the `sleep()` is added *after*  the tracer close, the spans are not sent. It looks like Close() must be failing to flush buffers, instead dropping any pending buffers on the floor.

Configuration, loaded with the YAML config support:

```
disabled: false
sampler:
    type: const
    param: 1
reporter:
    queueSize: 100
    bufferFlushInterval: 10
    logSpans: false
    localAgentHostPort: 127.0.0.1:6831
headers:
    jaegerDebugHeader: debug-id
    jaegerBaggageHeader: baggage
    TraceContextHeaderName: trace-id
    traceBaggageHeaderPrefix: "testctx-"
baggage_restrictions:
    denyBaggageOnInitializationFailure: false
    hostPort: 127.0.0.1:5778
    refreshInterval: 60
```
